name: galaxus
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - openssl=1.1.1
  - pip=20.0.2
  - python=3.8.1
  - setuptools=46.0.0
  - sqlite=3.31.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
